// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aumtfcsupedwridqrqma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1bXRmY3N1cGVkd3JpZHFycW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTM0NzMsImV4cCI6MjA2OTYyOTQ3M30.yj6_YWkwfxAMCdHFhYONk3b3ebPcCv5sZp52jUmI2vY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});